@startuml
Class User


Abstract Class BuildingMaterials
Class Wood extends BuildingMaterials
Class RoofTile extends BuildingMaterials
Class Fitting extends BuildingMaterials
Class Screw extends BuildingMaterials
Class Plans


Class BillOfMaterials

Class Carport
Class Order
Plans --o "1,,1"Carport
Wood --o "0,,many "BillOfMaterials
Fitting --o "0 ,,many " BillOfMaterials
RoofTile --o "0,,many  " BillOfMaterials
Screw --o "0,,many " BillOfMaterials
BillOfMaterials --o "1,,1"Carport
Carport "1"--o "1,,1" Order
Order --o "many,,1 "User


@enduml