@startuml
'https://plantuml.com/class-diagram

Abstract Class BuildingMaterials
Class Wood extends BuildingMaterials
Class RoofTile extends BuildingMaterials
Class Fitting extends BuildingMaterials
Class Screw extends BuildingMaterials

Class Orders
Class User
Class Material




@enduml